### ISSUE TITLE
 Cannot read properties of undefined (reading 'overlays')

### ISSUE THREAD

**Issue by dunkfordyce** [siemens/edgeshark#40]
Hi, 

I have used the given instructions to run edgeshark. The docker compose output looks normal as far as I can see but in the UI I hit refresh and it complains with this message at the bottom of the screen in red and this in dev console. Any idea what might be wrong?

```
Docker version 20.10.16, build aa7e414
```

```
TypeError: Cannot read properties of undefined (reading 'overlays')
    at index-Pv9-QzaM.js:1:13308
    at Array.forEach (<anonymous>)
    at index-Pv9-QzaM.js:1:12951
    at Array.forEach (<anonymous>)
    at us (index-Pv9-QzaM.js:1:12916)
    at index-Pv9-QzaM.js:1:21745
```

**Comment by dunkfordyce** [comment]
I have just tried on a different host with `Docker version 24.0.7, build afdd53b` with the same result.

**Comment by thediveo** [comment]
probably same as issue #39; can you give us some more details:
- which ghostwire version? This can be glanced from the container logs
- which distribution are you on?
- WSL2 and/or Docker Desktop?
- do you know if your networking setup includes VXLAN?

**Comment by thediveo** [comment]
Can reproduce with latest ghostwire image, so I can dig into this. As this is a duplicate of issue #39 I'm closing this one here and moving forward on the earlier reported issue.
